server:
  port: 8000
spring:
  application:
    name: cambio-service
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    password: postgres
    url: jdbc:postgresql://localhost/cambio_service
    username: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
  sleuth:
    sampler:
      probability: 1.0
  flyway:
    user: postgres
    password: postgres
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka 
      